name: "\U0001F4A1 Compatibility Fix"
description: Report an issue with Barabari Website
labels: ['compat']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the compatibility issue is. Add Expected Behavior if possible/applicable. Include platform details such as web, firefox etc where applicable
      placeholder: Bug description
    validations:
      required: true
  - type: checkboxes  # New field
    id: behind-demo-flag
    attributes:
      label: Configuration
      options:
        - label: A11y
        - label: I18n
        - label: SEO
        - label: Platform Specific
      description: Check boxes as applicable
    validations:
      required: false
  - type: textarea
    id: comments
    attributes:
      label: Comments
      description: Anything else to keep in mind?
      placeholder: Any additional context...
    validations:
      required: false
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Select the severity of this issue
      options:
        - annoyance (low priority)
        - minor impact (medium priority)
        - critical (high priority)
    validations:
      required: true
